Repository Cretezy/dSock, pull requests merged in 2020-05, with the labels that each got.

#2 Add error documentation, fix minor error code mismatch
  CHANGELOG.md
  README.md
  api/claim_handler.go
  common/errors.go
  common/token_middleware.go
Labels: bug, documentation

#3 Refactor errors, add better comments
  CHANGELOG.md
  api/claim_handler.go
  api/disconnect_handler.go
  api/info_handler.go
  api/main.go
  api/resolve_claims.go
  api/resolve_workers.go
  api/send_handler.go
  api/send_to_workers.go
  common/errors.go
  common/resolve_options.go
  common/token_middleware.go
  common/utils.go
  common/version.go
  worker/authentication.go
  worker/connect_handler.go
  worker/main.go
  worker/main_test.go.disabled
  worker/resolve_connections.go
  worker/send_handler.go
Labels: enhancement

#1 Add testing
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  api/Dockerfile
  api/claim_handler.go
  common/errors.go
  common/errors_test.go
  common/utils_test.go
  docker-compose.e2e.yml
  docker-compose.yml
  docs/releasing.md
  e2e/Dockerfile
  e2e/README.md
  e2e/api_utils_test.go
  e2e/connect_test.go
  e2e/disconnect_test.go
  e2e/info_test.go
  e2e/send_test.go
  e2e/test_utils_test.go
  go.mod
  scripts/run-e2e
  scripts/run-tests
  scripts/run-unit
  worker/Dockerfile
  worker/connect_handler.go
Labels: enhancement

#4 Replace scripts directory with Task
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  Taskfile.yml
  docs/releasing.md
  e2e/README.md
  scripts/build-binaries
  scripts/build-docker
  scripts/build-protos
  scripts/push-images
  scripts/run-e2e
  scripts/run-tests
  scripts/run-unit
Labels: enhancement

#5 Channels
  CHANGELOG.md
  README.md
  Taskfile.yml
  api/channel_handler.go
  api/claim_handler.go
  api/config.toml
  api/disconnect_handler.go
  api/info_handler.go
  api/main.go
  api/resolve_claims.go
  api/resolve_workers.go
  api/send_handler.go
  api/send_to_workers.go
  common/constants.go
  common/errors.go
  common/options.go
  common/protos/message.pb.go
  common/resolve_options.go
  common/utils.go
  e2e/api_utils_test.go
  e2e/channel_test.go
  e2e/connect_test.go
  e2e/disconnect_test.go
  e2e/info_test.go
  e2e/send_test.go
  e2e/test_utils_test.go
  protos/message.proto
  worker/authentication.go
  worker/channel_handler.go
  worker/config.toml
  worker/connect_handler.go
  worker/jwt.go
  worker/main.go
  worker/resolve_connections.go
  worker/send_handler.go
Labels: enhancement

#6 correct unsubscribe url in README file
  README.md
Labels: documentation

#7 Fix E2E (channel subscription delay)
  docs/releasing.md
  e2e/channel_test.go
Labels: bug

#11 Use Gin BindQuery
  CHANGELOG.md
  api/channel_handler.go
  api/claim_handler.go
  api/disconnect_handler.go
  api/info_handler.go
  api/send_handler.go
  common/errors.go
  common/resolve_options.go
  e2e/Dockerfile
Labels: enhancement

#10 Add locks
  CHANGELOG.md
  Taskfile.yml
  worker/channel_handler.go
  worker/connect_handler.go
  worker/main.go
  worker/resolve_connections.go
  worker/state.go
Labels: enhancement
